### ISSUE TITLE
Methods select and getSelected for ComboBox element don't work.

### ISSUE THREAD

**Issue by Aks1389** [epam/JDI#17]
select(__any_string__) returns 

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.AssertionError: 'Value' element for dropdown not defined
    at com.epam.commons.Timer.wait(Timer.java:128)
    at com.epam.commons.Timer.alwaysDoneAction(Timer.java:90)
    at com.epam.jdi.uitests.web.selenium.elements.actions.ActionInvoker.doJAction(ActionInvoker.java:74)
    at com.epam.jdi.uitests.web.selenium.elements.actions.ActionInvoker.doJAction(ActionInvoker.java:70)
    at com.epam.jdi.uitests.web.selenium.elements.actions.ElementsActions.select(ElementsActions.java:150)
    at com.epam.jdi.uitests.web.selenium.elements.complex.Selector.select(Selector.java:50)
```

getSelected() returns NullPointerException.

**Comment by Supreme85** [comment]
Can you show your Dropdown description?
Hope you just not specify isSelected for it
