### ISSUE TITLE
StaleElementReferenceException at Selector select method

### ISSUE THREAD

**Issue by BelAn97** [epam/JDI#174]
If I try to select item before the page was fully update I got StaleElementReferenceException after timeout. 

INFO: Select 'Quick' for Menu 'Nav Menu' (SearchPage.navMenu; ; cssSelector='#horizontalNav .embs-nav__item')

java.lang.RuntimeException: java.lang.AssertionError: Do action Select 'Quick' failed. Can't get result. Reason: java.lang.RuntimeException: java.lang.AssertionError: Do action Click on Element failed. Can't get result. Reason: org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'EPRUPETW6024', ip: '10.66.9.120', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506120 (e3e53437346286..., userDataDir: C:\Users\ANDREI~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 62.0.3202.94, webStorageEnabled: true}
Session ID: 4dc1cfba47d21a3d90b5996b11e3e7d8

	at com.epam.commons.Timer.wait(Timer.java:128)
	at com.epam.commons.Timer.alwaysDoneAction(Timer.java:90)
	at com.epam.jdi.uitests.web.selenium.elements.actions.ActionInvoker.doJAction(ActionInvoker.java:73)
	at com.epam.jdi.uitests.web.selenium.elements.actions.ActionInvoker.doJAction(ActionInvoker.java:69)
	at com.epam.jdi.uitests.web.selenium.elements.actions.ElementsActions.select(ElementsActions.java:151)
	at com.epam.jdi.uitests.web.selenium.elements.complex.Selector.select(Selector.java:55)

**Comment by Supreme85** [comment]
Need more info for reproduce. Maybe site example or steps to reproduce.
