### ISSUE TITLE
SmokeTest -  java.lang.AssertionError: Do action Select 'CAREERS' failed 

### ISSUE THREAD

**Issue by skabashnyuk** [epam/JDI#55]
I have 
```
java.lang.RuntimeException: java.lang.AssertionError: Do action Select 'CAREERS' failed. Can't get result. Reason: java.lang.AssertionError: Can't find option 'CAREERS'. Please fix allLabelsLocator

	at com.epam.commons.Timer.wait(Timer.java:128)
	at com.epam.commons.Timer.alwaysDoneAction(Timer.java:90)
	at com.epam.jdi.uitests.web.selenium.elements.actions.ActionInvoker.doJAction(ActionInvoker.java:73)
	at com.epam.jdi.uitests.web.selenium.elements.actions.ActionInvoker.doJAction(ActionInvoker.java:69)
	at com.epam.jdi.uitests.web.selenium.elements.actions.ElementsActions.select(ElementsActions.java:149)
	at com.epam.jdi.uitests.web.selenium.elements.complex.Selector.select(Selector.java:55)
	at com.epam.jdi.uitests.web.selenium.elements.complex.Selector.select(Selector.java:63)
	at org.mytests.tests.SmokeTest.oneActionTest(SmokeTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.AssertionError: Do action Select 'CAREERS' failed. Can't get result. Reason: java.lang.AssertionError: Can't find option 'CAREERS'. Please fix allLabelsLocator
	at org.testng.Assert.fail(Assert.java:94)
	at com.epam.web.matcher.base.BaseMatcher.assertException(BaseMatcher.java:194)
```
Running on MacBook Pro (Retina, 13-inch, Early 2015)
I think it's because of screen size 
<img width="1440" alt="2017-01-31 22 53 03" src="https://cloud.githubusercontent.com/assets/1614429/22484054/6a30e718-e808-11e6-97bc-3a523317913b.png">
When I uncomment ```#browser.size=1800X1000``` its start working

**Comment by Supreme85** [comment]
This is correct test fail. Not a problem of JDI
You try to click on element which not exist on page => test fails
